### ISSUE TITLE
Unable to get events?

### ISSUE THREAD

**Issue by huehueteotl** [giachello/mlgw#16]
Hi,

I obtained a 2nd hand ML Gateway via e-Bay to control my BeoVision 7-55 (Mk1) and integrate with HA.
But no matter what I try, I'm unable to get the BV-7 detected in the devices list, and see nothing in the _mllog monitor!

Not sure it's relevant in my case but the BV-7 is in option 1 mode and I'm unable to change that setting.
I have enabled the "STATS TO MLGW" and "CMDS TO MLGW" options under de ADJUSTMENST of the Customer Service Menu.

Do you have any tips of what I can try next?

**Comment by oskarax** [comment]
Have you done the add procedure and putt the MLGW in pairing mode and turning the TV on and let the MLGW discover the TV?

**Comment by huehueteotl** [comment]
Yes, sure: both using the webintf and the manual setup-button press to get it in setup mode.
But no matter what sources I select (I just use an Apple TV on V.MEM 100% of the time) nothing is detected!

Like I said: if I open the "monitor" or lower-level "_mllog" option directly on the CLI via telnet there is just nothing happening; no events/codes/keys whatsoever.

**Comment by giachello** [comment]
Hi there. It's hard to debug without access to the device, but this is what I'd try:

1. Factory reset and update mlgw to latest sw version

2. Pair the TV with the MLGW (seems you already did this)

3. The 7-55 is supposed to forward light commands to the MLGW, according [to this doc](http://mlgw.bang-olufsen.dk/source/documents/Setting up products to MLGW/MLGW set-up in A1.docx)

In order for the light commands to go through you need to set up a room on the MLGW and tell it that the TV is in that room. Otherwise, the Light commands won't go through.

You need to probably also enable MLGW commands on the TV in some way.

4. Is the TV connected to the MLGW through Masterlink or Network Link (i.e. Ethernet)?

Even if it is connected via Masterlink I noticed that TVs don't always transmit events to the Masterlink, especially if they are local events (e.g., a local source selection).

5. Network Link connected devices only forward Light events, not master link events. 

6. Test the B&O app to see if you can turn on / control the TV from it. That would tell you if that direction communication works.

**Comment by huehueteotl** [comment]
Hi, thanks for taking the time to help with this.

1. Done that, my MLGW (type 1798/1799) is on version 2.24b (2014-1-17)

2. _that is actually the core problem!_
No matter how I start the setup/pairing (at least I assume this is the same procedure we're talking about?) the MLGW stays in scanning mode and does not find any device.

3. → Yes: I have the settings as in that document; both "TO MLGW" options are ON

> You need to probably also enable MLGW commands on the TV in some way.
Yes, but how? I can't find anything on this, except the (rather vague to me) "OPTION" settings but those only seem to be relevant in multi-room/multi-remote control setups which I don't have/
From the sparse and ancient info I can find it sounds like the MasterLink port is always active and the BV7 is always in "OPTION 1" mode?

Do you have the correct/detailed pairing procedure I should follow?

4. → I only have the BV7-55 with a BeoLab 7.1 center speaker and two BeoLab 5's.
All speakers are connected thru PowerLink, none of these supports any Net/Masterlink (+11 yrs old now!).
Powering off, selecting a source (they're all local) does not trigger anything on the MLGW.

The MLGW is connected thru the only option available on the BV7-55 Mk1: the MasterLink connector.
I was under the impression the CLI monitor/_mllog commands would show anything sent over the cable?
If the "pairing" needs to be completed 1st, I honestly have no idea how to fix that.

5. n.a.

And 6: yes please, but how? The BV7-55 Mk1 is not "smart" by default, so I would need to have the MLGW working 1st before I can use the B&O App?

The "allstandby" function which the MLGW docs say to use for testing does not do anything in my case too.

It starts to sound like the MLGW or the cable are broken, but somehow I refuse to believe that. I "beeped" the cable wires with a multi-meter and all seems to be correct.

**Comment by giachello** [comment]
I was also thinking the cable or the interface may be broken.  I've also had some issues with the connectors not making contact in the past. 

The inclusion process is started on mlgw and then you should turn on each device in sequence. It should automatically turn off the device that you turn on to show that it 'got it'.  Do you have any other master link equipment to test your TV or MLGW?

**Comment by huehueteotl** [comment]
> Have you tried unplugging power to both devices before doing the inclusion? As opposed to plugging them with masterlink cable while on.

We live in the Tuscan countryside and there are often blackouts of power, so I've "done" this multiple times :-D
I have no other device to connect the gateway to, so not easy to find out who's the culprit.

I'll try to contact the guy I bought the gateway from (B&O classic shop in AT) to see if he has any tips.
Thanks for your time anyway!
